services:
    app.locale_listener:
        class: Recognize\AdminThemeBundle\EventListener\SessionLocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    app.fosuser_listener:
        class: Recognize\AdminThemeBundle\EventListener\FOSEventListener
        arguments: ["@twig", "@session"]
        tags:
            - { name: kernel.event_subscriber }

    recognize.admintheme.form.type.switch:
         class: Recognize\AdminThemeBundle\Form\Type\SwitchType
         tags:
            -  { name: form.type, alias: "switch" }

    recognize.admintheme.form.type.removable_file:
         class: Recognize\AdminThemeBundle\Form\Type\RemovableImageType
         arguments: ["@request_stack"]
         tags:
            -  { name: form.type, alias: "removable_file" }

    twig.recognize.admintheme.variables:
         class: Recognize\AdminThemeBundle\Service\AdminthemeTwigInitializer
         arguments: ["%recognize_admin_theme.config%", "@twig", "@security.token_storage", "@session"]
         tags:
            -  { name: twig.extension }

    twig.recognize.admintheme.tablefunctions:
        class: Recognize\AdminThemeBundle\Twig\TableFunctions
        arguments: ["@service_container"]
        public: false
        tags:
             - { name: twig.extension }
